services:

  db:
    image: 'postgres:14-alpine'
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_DB=tofu
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5555:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"