class ProductDetailsResponse {
  int? id;
  String? title;
  String? description;
  String? image;
  double? price;
  String? publicationDate;
  String? state;
  bool? shippingAvailable;
  bool? sold;
  String? platform;
  List<String>? category;
  String? address;
  double? userScore;

  ProductDetailsResponse(
      {this.id,
      this.title,
      this.description,
      this.image,
      this.price,
      this.publicationDate,
      this.state,
      this.shippingAvailable,
      this.sold,
      this.platform,
      this.category,
      this.address,
      this.userScore});

  ProductDetailsResponse.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    description = json['description'];
    image = json['image'];
    price = json['price'];
    publicationDate = json['publication_date'];
    state = json['state'];
    shippingAvailable = json['shipping_available'];
    sold = json['sold'];
    platform = json['platform'];
    category = json['category'].cast<String>();
    // if (json['category'] != null) {
    //   category = <Category>[];
    //   json['category'].forEach((v) {
    //     category!.add(new Category.fromJson(v));
    //   });
    // }
    address = json['address'];
    userScore = json['userScore'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['description'] = this.description;
    data['image'] = this.image;
    data['price'] = this.price;
    data['publication_date'] = this.publicationDate;
    data['state'] = this.state;
    data['shipping_available'] = this.shippingAvailable;
    data['sold'] = this.sold;
    data['platform'] = this.platform;

    // if (this.category != null) {
    //   data['category'] = this.category!.map((v) => v.toJson()).toList();
    // }
    data['category'] = this.category;
    data['address'] = this.address;
    data['userScore'] = this.userScore;
    return data;
  }
}

// class Category {
//   int? id;
//   String? genre;

//   Category({this.id, this.genre});

//   Category.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     genre = json['genre'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['genre'] = this.genre;
//     return data;
//   }
// }

class ProductResponse {
  late int id;
  String? title;
  String? image;
  double? price;
  String? publicationDate;
  String? state;
  String? platform;
  List<String>? category;
  String? description;

  ProductResponse({
    required this.id,
    this.title,
    this.image,
    this.price,
    this.publicationDate,
    this.state,
    this.platform,
    this.category,
    this.description,
  });

  ProductResponse.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    image = json['image'];
    price = json['price'];
    publicationDate = json['publicationDate'];
    state = json['state'];
    platform = json['platform'];
    category =
        json['category'] != null ? List<String>.from(json['category']) : null;
    description = json['description'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['image'] = this.image;
    data['price'] = this.price;
    data['publicationDate'] = this.publicationDate;
    data['state'] = this.state;
    data['platform'] = this.platform;
    data['category'] = this.category;
    data['description'] = this.description;
    return data;
  }
}


// Generated by https://quicktype.io




