services:
  db:
    image: 'postgres:14-alpine'
    container_name: GamesForAll
    restart: always
    environment:
      - POSTGRES_DB=games
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=1234
    ports:
      - "5555:5432"