name: gamesforall_frontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: '>=3.0.0-261.0.dev <4.0.0'


dependencies:
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  flutter_form_bloc: ^0.30.1
  equatable: ^2.0.5
  http: ^0.13.5
  get_it: ^7.2.0
  injectable: ^2.1.0
  http_interceptor: ^1.0.1
  shared_preferences: ^2.0.17
  eva_icons_flutter: ^3.0.0
  google_fonts: null
  google_nav_bar: ^5.0.6
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.1.0
  uuid: ^3.0.0
  rxdart: ^0.27.3
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3  
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0   

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

